### ISSUE TITLE
Uncaught TypeError: exec is not a function

### ISSUE THREAD

**Issue by pruett** [wildbit/postmark.js#1]
I'm requiring this package and bundling the scripts together with browserify. When I `require('postmark')`, I'm seeing this error in the console

```
Uncaught TypeError: exec is not a function
```
pointing to the following function:

```js
function _command(cmd, cb) {
  exec(cmd, function(err, stdout, stderr) { // this line reports the error
    cb(stdout.split('\n').join(''))
  }
  )
```

Any ideas?

**Comment by pruett** [comment]
Scratch that, I think this is just an issue with me calling it client-side instead of from a node.js server. Sorry about that, pulled the trigger too quick!

**Comment by atheken** [comment]
@pruett, glad you sorted it out!

Just for future reference: Even if one were to substitute in their own "http request shim", it would be blocked by the browser due to CORS restrictions. This is done on purpose, because using the Postmark API from a browser would require people to expose their server and/or account tokens to (probably untrusted) clients, which is not a good idea.

Please let us know how your experience using postmark.js in node works out!
