### ISSUE TITLE
Breaking changes in 3.0?

### ISSUE THREAD

**Issue by stephent** [wildbit/postmark.js#102]
I'm assuming there are breaking changes given the major version number hike, but the [release notes](https://github.com/wildbit/postmark.js/releases/tag/3.0.0) don't specify exactly what has changed and what a developer would need to do to upgrade successfully. Any chance that could be added somewhere? Thanks!

**Comment by ibalosh** [comment]
Hi

there are no breaking changes in v3, upgrade will not affect library usage in any way. That is why there are no additional notes about it.

However, v3 decouples http client completely from the postmark client compared to v2.x so we can easily switch from axios if needed in future. Since this affects the core of the library and every operation, we upgraded version to v3. Its not 100% semver compatible but the change is significant and therefore we decided to name it v3.

**Comment by stephent** [comment]
@ibalosh thanks for clarifying. It would be useful to state explicitly "no breaking changes" in the release notes, as the default expectation of most developers on seeing a major version bump is that there *are* breaking changes.

**Comment by ibalosh** [comment]
Hi @stephent 

we do have a note that there is no breaking changes in GH release notes: https://github.com/wildbit/postmark.js/releases/tag/3.0.0 and in wiki documents https://github.com/wildbit/postmark.js/wiki/Migrating-from-1.x-to-2.x-version .

Any other location for the note you had in mind, that might be missing in our documentation update?

**Comment by stephent** [comment]
@ibalosh - apologies, I missed the comment [here](https://github.com/wildbit/postmark.js/releases/tag/3.0.0). 

However, I'm not sure what the relevance of the 1.x to 2.x migration note is? We're talking about 2.x to 3.x.

I'll reiterate that I think sticking to semver conventions is the best approach to avoid confusion.

**Comment by ibalosh** [comment]
Hey @stephent 

I completely agree, we will make adjustments in documentation. However, things are not always black and white. If we would stick to semver blindly, we would not even move from version 1. Even though the library completely changed from 1 to version 2, changes were compatible. You could still initialise and use the library the old way. All the API endpoints were compatible, with addition of new one.

Version 3 was significant, we moved whole version for Typescript, completely changed the way we use error handling, decoupled the client. Changes were compatible again. I would say those are pretty significant changes - probably not as big as move from 1 to 2, but the biggest change we did since then that affects the library. Therefore it would be weird to stay on version 2 or version 1 because there are no incompatible changes.
