### ISSUE TITLE
update readme to mention template API

### ISSUE THREAD

**Issue by hybernaut** [wildbit/postmark.js#11]
I was preparing to implement template API support, but it's already in there!  I'll update the README to list all the supported API methods.

**Comment by atheken** [comment]
Hey there! We actually cover all of that in the documentation: https://wildbit.github.io/postmark.js/ (browsing the classes there shows everything the client can do).

I've updated the README to reflect that postmark.js has complete REST API coverage, so that should make it more obvious that we've already done the heavy lifting. :-)

**Comment by hybernaut** [comment]
thanks for doing this, @atheken. I hope more people are encouraged to use this library.
