### ISSUE TITLE
Child process breaks in electron. And, is bug when installed via npm? `git rev-parse HEAD`

### ISSUE THREAD

**Issue by willhoag** [wildbit/postmark.js#29]
In file `lib/postmark/clientDefaults.js`

Lines 7-9:
```js
exec('git rev-parse HEAD', { cwd: __dirname }, function (err, stdout, stderr) {
 sha = stdout.split('\n').join('') || 'unknown revision';
});
```

When installed via `npm` there is no git repo included and `git rev-parse HEAD` searches up the tree till it hits one, so this would return the shaw for whatever individual's git repo it was installed in if any.

Either way in Electron, I get a ENOTDIR error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: spawn ENOTDIR
    at exports._errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:505:9)
    at Object.exports.execFile (child_process.js:220:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:199:20)
    at exports.exec (child_process.js:150:18)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at Object.<anonymous> (~/App/Contents/Resources/app.asar/node_modules/postmark/lib/postmark/clientDefaults.js:7:1)
    at Object.<anonymous> (~/App/Contents/Resources/app.asar/node_modules/postmark/lib/postmark/clientDefaults.js:126:3)
    at Module._compile (module.js:569:30)
```

**Comment by atheken** [comment]
Welp. This is embarrassing. The intention of getting the git rev was to include it in the User-Agent when the client makes requests to our API, allowing us to analyze our request logs to understand which versions of our libraries our customers are using. We wanted the git rev for the postmark lib if we ever needed to track down version specific bugs.

That was the intention. As it turned out, we never got to the point of adding those analytics (in the years since we released this lib, we actually never needed to check that..)

At any rate, this is just a bug that needs fixing.

---

*Having said all of that*, I would really advise against including your server token/sending directly from an electron app, if you plan to distribute it. The reason is that it is probably trivially easy to get out of the app bundle,  allowing anyone to send using your Sender Signatures in Postmark. The recommended approach would be to set up an endpoint on a server you control, and have the electron  app trigger an email from there.

**Comment by willhoag** [comment]
Hi @atheken,

Thanks for the quick response. I figured as much with the bug: could see the intention and know why these things can linger in code as long as they do.

As for the electron app, it isn't meant for distribution as we use it internally only. It will someday live on a server, and in fact the postmark lib runs in a server spun up inside the app currently, with plans to move further into development.

As it stands, before packaging I comment out the lines above. Would love nix that step since it's not automated. Perhaps it's not the general use case, so I understand it's not likely a high priority. But, since it doesn't work as intended and you don't seem to be using it, maybe I can get a win via happenstance?

**Comment by atheken** [comment]
It’s already removed from master, and I’ll publish an update in the next couple days.

//Andrew

**Comment by willhoag** [comment]
Lovely and much obliged.

![thanks](https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)
