### ISSUE TITLE
CORS Error with test code.

### ISSUE THREAD

**Issue by TimMeade** [wildbit/postmark.js#46]
I am running the very simple test code.    It immediately returns:

Access to fetch at 'https://api.postmarkapp.com//email' from origin 'http://10.1.1.140:3111' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I can not find anywhere to set the CORS endpoints.  Am i missing something simple?

**Comment by rianvdm** [comment]
Hi @TimMeade, can you please email support@postmarkapp.com with the details? Our team will be able to assist you more easily there.

**Comment by atheken** [comment]
Just to clarify on this specific issue. The `postmark.js` library does not support accessing the Postmark API via a browser context. This is because it would require you to expose your server token in the client javascript, and therefore anyone using the app would have access to your Postmark Server. Instead, we recommend you proxy requests to your server, validate them (check the email address of the user, for example), and then allow your server to make the request to the Postmark API. This keeps your server token secure. We recognize this limits use of Postmark in SPAs based on React and Angular, etc, but this is our current recommendation to keep your Postmark token secure.

**Comment by TimMeade** [comment]
Thanks that was exactly what i was doing.
