### ISSUE TITLE
sendEmailBatchWithTemplates not reporting errors

### ISSUE THREAD

**Issue by vinczebalazs** [wildbit/postmark.js#47]
Hello!

I am using the `sendEmailBatchWithTemplates` method of the `ServerClient` class and noticed that the returned Promise still resolves successfully even in the case of an error. 
To reproduce it, I tried sending an email with a `From` address which is not in my Sender Signatures. When using the exact same template but with the `sendEmailWithTemplate` method, I get the following error: 
`"The 'From' address you supplied (test@test.com) is not a Sender Signature on your account. Please add and confirm this address in order to be able to use it in the 'From' field of your messages.","code":400`

However, when using the `sendEmailBatchWithTemplates` method with the exact same template (wrapped in an array) and `From` address, the mail never makes it to the Postmark API (it does not show up in my activity log), but the Promise is still resolved successfully, no errors are thrown.

Please look into this issue as methods which fail silently make debugging very difficult.

Thank you!

**Comment by ibalosh** [comment]
Hi @vinczebalazs , 

postmark javascript library is only passing through what it gets from Postmark API. Unforunatelly it won't throw an error in this case, since it's the way [Postmark API](https://postmarkapp.com/developer/user-guide/sending-email/sending-with-api) works.

With batches, you are sending multiple email messages, it can be more than 10-20, or even 100 of them. Each of these can have a unique error or some might not have errors. Therefore API can't return a unique error to relly on. That is why batch calls would return a 200 http status, but you are able to investigate each response of array of messages being sent and generate custom handling for these.

**Comment by alizbazar** [comment]
Hi @ibalosh ,

When you mentioned 

> but you are able to investigate each response of array of messages being sent and generate custom handling for these.

What do you mean? How should one make sure that the messages were actually sent, and if not, for what reason?

**Comment by ibalosh** [comment]
Hey @alizbazar 

when you send a message, using batch endpoints (including sendEmailBatchWithTemplates), the response will be always success from API. The response will be looking something like this

```
[
    {
        "To": "igor@wildbit.com",
        "SubmittedAt": "2019-05-08T15:51:37.3718827-04:00",
        "MessageID": "01bebc61-45d0-4de6-af36-50705f516f3e",
        "ErrorCode": 0,
        "Message": "OK"
    },
    {
        "ErrorCode": 406,
        "Message": "You tried to send to a recipient that has been marked as inactive.\nFound inactive addresses: nothing@bounceaddress.com.\nInactive recipients are ones that have generated a hard bounce or a spam complaint. "
    }
]
```

To check whether your email was sent, you can check the response which contains array of all message send responses. In the case above, email was sent to first address, but wasn't to second. 

These should be easy to handle. Since for batch sends, response is always an array, API will not throw an error, but rather a response with array of send responses to check.
