### ISSUE TITLE
Import with babel returns undefined

### ISSUE THREAD

**Issue by pierreinglebert** [wildbit/postmark.js#52]
When importing postmark with "import" keyword using babel transpiler, the library is undefined.

I created a Gist to reproduce the error : https://gist.github.com/pierreinglebert/0db4fdf08e93b775be12120575f0b3f2

(It worked well with 1.x)

I'm using Node 12.

**Comment by alex-sherwin** [comment]
Observing the same thing, to get some semblance of type safety when using TypeScript I'm working around like so:

```typescript
const postmark = require("postmark");
import * as PostmarkTypes from "postmark";

const client: PostmarkTypes.ServerClient = new postmark.ServerClient("mykey");

```

**Comment by ibalosh** [comment]
Hi guys,

the reason for this is since from version 2, library was moved to Typescript and at the same time, default export "postmark" was removed.

Therefore the way to import the postmark library in case you are using ES6 way of importing would be the one @alex-sherwin mentioned:

import * as postmark from "postmark";
const client: postmark.ServerClient = new postmark.ServerClient("mykey");

(I think require part is not needed)

the full model of things that can be imported can be found here:

https://github.com/wildbit/postmark.js/blob/master/src/index.ts

Let us know if we should updated our docs, in migration and getting started sections to make this bit more clear:

https://github.com/wildbit/postmark.js/wiki/Migrating-from-1.x-to-2.x-version
https://github.com/wildbit/postmark.js/wiki/Getting-Started

We used in our examples the old style of import to make it work for most of the users.

**Comment by jasonhargrove** [comment]
Copied 1x code from one API into a second API and upgrade to 2x. The awkward thing is that errors were not reported. Thanks to this issue I figured it out.

Docs on these pages are not accurate:

https://github.com/wildbit/postmark.js/wiki/Templates
https://github.com/wildbit/postmark.js/wiki/Getting-Started

**Comment by ibalosh** [comment]
Hi @jasonhargrove 

thank you for reporting this, we will see to make updates accordingly. Could you share details which part of the doc is inaccurate and caused silent errors when trying to migrate?

Please share library 2x version you were upgrading to, too.

Thanks,
Igor

**Comment by natac13** [comment]
> @ibalosh It would probably be good to mention in https://github.com/ActiveCampaign/postmark.js/wiki/Getting-Started that the library should be imported as `import * as postmark from "postmark"`.

I just ran into this same issue as well

**Comment by ibalosh** [comment]
thanks, I have updated the documentation to include ES6 style of imports too

**Comment by mleonhard** [comment]
Here's the full error, for future searchers:
```
TypeError: Cannot read properties of undefined (reading 'Client')
TypeError: Cannot read properties of undefined (reading 'ServerClient')
```

To reiterate, the problem is that the default module export doesn't work with TypeScript.  The workaround is to import like this:
```typescript
import * as postmark from 'postmark'
```
