### ISSUE TITLE
testing API key not enough with sendEmailWithTemplate method

### ISSUE THREAD

**Issue by Oloompa** [wildbit/postmark.js#56]
Hi,

I implement test. I use `process.env.POSTMARK = "POSTMARK_API_TEST";`

in [documentation](https://postmarkapp.com/blog/handling-email-in-your-test-environment) i can read: 

>  it helps ensure that your messages will be accepted by the API

Sadly, if it help to init postmark library without any error, it doesn't allow me to call `sendEmailWithTemplate()` method. I got the following error:

```typescript
ApiInputError {
    code: 1101,
    statusCode: 422,
    message: 'The Template\'s \'Alias\' associated with this request is not valid or was not found.',
  }
```

I used `welcome` as alias. Any well formed alias should be ok as i am using the test API key.

**Comment by atheken** [comment]
Hi @Oloompa

The issue here is that this type of test is not currently possible within the Postmark API. This is because, in order to validate a template sending request, we need to be able to match your API call against your Postmark Server. Normally we would do this with your server token, but with the test api key, there is no way to verify that `welcome` is a template associated with your server.

This is definitely something we're aware of as needing improvement in our API, but not an issue with this specific library. If you'd like some guidance on how to test, please feel free to contact support and they can give you some suggestions.
