### ISSUE TITLE
Domain verification issues

### ISSUE THREAD

**Issue by barclayadam** [wildbit/postmark.js#63]
Hi,

I'm integrating Postmark into our Pulumi infrastructure scripts. As part of that I wish to verify the domains' DKIM and ReturnPath setup but have come across a couple of issues relating to the return values:

`client.verifyDomainReturnPath`:

 - Even if the UI shows return path has validated `ReturnPathDomainVerified` is `false`
 - Once validated the API returns `SPFVerified` as `true`. The response has incorrect casing of `SpfVerified` though, which is `undefined`. I work around using `(response as any).SPFVerified` in TypeScript

`client.verifyDomainDKIM`:

 - The `DKIMVerified` field is never `true`, even if `DKIMUpdateStatus` is equal to `Verified`

I've worked around these issues, but likely to catch others out. I'm using v2.5.3

**Comment by ibalosh** [comment]
Hi @barclayadam 

regarding the SPF fields, I updated the model (in 2.5.4) , so it returns proper results. However, I strongly advise not to use those fields since they are left in just for backward compatibility of the API.

As for the DKIM and for Return Path, for being completely sure that they are verified, you should rely in API on DKIMVerified and ReturnPathDomainVerified fields or on the emails which are sent to owner once the DKIM and RP are verified and in place for email sending. I checked the fields locally through node.js library and they worked correctly.

One note though, UI doesn't show the complete verification. UI shows that DKIM, RP domain is verified for sending email, but the usage of DKIM, RP keys in your sending might need more time - API verification shows that. This process might need more time, for new keys couple of minutes, up to 10, for older key it might need more, since they don't have priority.

If you are still seeing issues with verification DKIM, RP keys, not seeing them verified by API, please contact our support to check your account. The issue then is probably outside of the scope of the library and we would need to dig into more details in your account specifics.
