### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by ManalLiaquat** [wildbit/postmark.js#67]
Getting this error when running the server (`nodemon server.js`)
```
C:\<USER>\~\server\node_modules\postmark\dist\client\BaseClient.js:22
        this.token = token.trim();
                           ^

TypeError: Cannot read property 'trim' of undefined
    at ServerClient.BaseClient (D:\Manal Files\Office-Work\closebuy\server\node_modules\postmark\dist\client\BaseClient.js:22:28)
```

**version: ^2.6.0**

**Comment by ibalosh** [comment]
Hi @ManalLiaquat 

it seems that server token is not set when you initialize your client. Are you passing token as stream value? Could you share details how you initialize your postmark server or account client?

Igor

**Comment by taraldjoh** [comment]
Hi @ManalLiaquat 

I had the similar issue when I installed my project on an Ubuntu laptop.

I resolved this by adding the Server API token to my configuration files so that it was initiated when starting up the project. This eliminates the error, so it's probably because you have yet to add your api token to your project configuration.

Please let me know if this was helpful! 

Kind Regards
Tarald Johansen
