### ISSUE TITLE
Setting "from name" in sendEmailWithTemplate

### ISSUE THREAD

**Issue by tyrw** [wildbit/postmark.js#83]
Unclear how to set the "From Name" field using the Postmark.js library. 

We have tried sending with [sendEmailWithTemplate](https://wildbit.github.io/postmark.js/classes/serverclient.html#sendemailwithtemplate)

```js
sendEmailWithTemplate({
  "From": "Full Name <sender@domain.com>",
  ...
})
```

as per https://postmarkapp.com/developer/api/templates-api#email-with-template

But we receive the error

`Error parsing 'From': Illegal email address 'Full'. It must contain the '@' symbol.`

Is it possible to set the from name with this library?

**Comment by ibalosh** [comment]
Hi @tyrw 

are you sure you correctly set the string when sending? Could it be it was escaped incorrectly so that you get the error? I tried it locally and could not see the issue.

<img width="757" alt="response" src="https://user-images.githubusercontent.com/14041/139667842-2d516d19-53cc-4d02-bfe4-7c6e0fec8347.png">

**Comment by tyrw** [comment]
Thanks @ibalosh for your reply. We haven't changed anything and it's working now, so perhaps it was related to the ongoing service issues. Will let you know if there are more issues.
