### ISSUE TITLE
BlockedReason in inbound message payload

### ISSUE THREAD

**Issue by krivachy** [wildbit/postmark.js#97]
We receive inbound webhooks from Postmark and use the `PostmarkModels.InboundMessageDetails` type to parse it.

We noticed that `BlockedReason` isn't present on the incoming JSON: https://github.com/wildbit/postmark.js/blob/c8b063b1148683c6a3ca7d50605cc20fb1521a25/src/client/models/messages/InboundMessage.ts#L35

Is this a mistake? Or is there a better model we should be using?

Thanks!

**Comment by krivachy** [comment]
I've opened a tiny draft PR for this.

**Comment by ibalosh** [comment]
Hi @krivachy 

BlockedReason will be always present, in case there is no block reason, the field will be a blank string. Due that field is not optional since it will be always returned. We have just checked the response. If in some cases you receive something else, please contact our support with specifics like account message id and we will check what could be causing that.

Igor
